id: I50831532
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:41:50+00:00'
last_modified: '2022-06-08T10:23:57.300197+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC406
  title: རྒྱ་བོད་དབྱིན་གསུམ་གསར་བྱུང་རྒྱུན་བཀོལ་མིང་མཛོད།༼ཁ་སྐོང་དེབ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    CC64:
      image_group_id: I2PD16875
      title: ''
      total_pages: 286
      order: 1
      base_file: CC64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
